api:
  name: base
  version: 1.0
endpoints:
  - path: path1
    methods:
      - GET
      - PUT
    description: This is a test Description
  - path: path2
    methods:
      - GET
      - PUT
    description: This is a test Description
