[cfg]
table = "shop"
path = "/shop"

[[field]]
name = "ID"
datatype = "i32"
primary_key = true

[[field]]
name = "Title"
datatype = "String"
nullable = false

[[field]]
name = "Value"
datatype = "String"
nullable = false

[shop.endpoints.list]
method = "GET"
path = "shops"

[shop.endpoints.create]
method = "POST"
path = "shops"
body = "shop"